### ISSUE TITLE
Status of this Project, Optimisation and increase of resolution

### ISSUE THREAD

**Issue by hmelder** [dj311/epd-wm#12]
Hi,

thank you for publishing this great project!
It is really impressive what you managed to do via a USB connection.

Now, are there any updates to this project or did you abandon it?
I would like to hack on the input lag problem as long as there is any chance of optimising it:
The 9.7" EPD from waveshare has a fairly low resolution (1200x825) but there are panels with a higher resolution (1872×1404). Is there a bottleneck when sending framebuffer data via USB to the IT8951? _An increase in the display's resolution might hurt performance even more._

Best Regards

Hugo Melder

**Comment by dj311** [comment]
Hi Hugo, 

This project has been abondoned by me. Mostly because I'm a relative newbie to C and the various tooling needed to manage dependancies. Getting it to build on newer versions of e.g. Ubuntu was a constant hassle for me.

With that said, the code does work and it's not too bad. I'd be keen to give you a hand getting it back up and running if you'd like. Expecially if you have a better understanding than I around C packaging.

> Is there a bottleneck when sending framebuffer data via USB to the IT8951? An increase in the display's resolution might hurt performance even more.

If I remember correctly, the amount of data being transferred wasn't a massive issue. There is an inherent latency every time you want to send a message, so sending more messages will be slower. But sending the same number of messages with more data in them should be fine. That's the USB <-> IT8951 part of the picture anyway.

The actually display refreshing part is a bit more of a mystery. I've been able to get *much faster* refreshes in certain cases (epd_demo.c in this repo for example). But I haven't been able to replicate those speeds in this repository, once all the infrastructure around it is in place.

My understanding (if I remember correctly from the last time I looked into it), is that the primary source of latency was actually from getting frames off the GPU, then onto the CPU for sending to the USB device. (This caused like a 100ms delay sometimes).

This is something that I believe is fixable by using different system calls (and making some trade-offs). But I haven't had the time to investigate this properly.

Best,
Dan

**Comment by hmelder** [comment]
Thank you for the comprehensive explanation. It looks like the amount of time required to optimise the sending of framebuffer data is huge but very interesting non the less. I'm actually thinking about buying a waveshare hdmi (fpga based) panel. What do you think?

​​​​
On Wednesday, November 17, 2021 12:34 CET, Dan Jones ***@***.***> wrote:
 
 
Hi Hugo,
This project has been abondoned by me. Mostly because I'm a relative newbie to C and the various tooling needed to manage dependancies. Getting it to build on newer versions of e.g. Ubuntu was a constant hassle for me.
With that said, the code does work and it's not too bad. I'd be keen to give you a hand getting it back up and running if you'd like. Expecially if you have a better understanding than I around C packaging.
Is there a bottleneck when sending framebuffer data via USB to the IT8951? An increase in the display's resolution might hurt performance even more.
If I remember correctly, the amount of data being transferred wasn't a massive issue. There is an inherent latency every time you want to send a message, so sending more messages will be slower. But sending the same number of messages with more data in them should be fine. That's the USB <-> IT8951 part of the picture anyway.
The actually display refreshing part is a bit more of a mystery. I've been able to get much faster refreshes in certain cases (epd_demo.c in this repo for example). But I haven't been able to replicate those speeds in this repository, once all the infrastructure around it is in place.
My understanding (if I remember correctly from the last time I looked into it), is that the primary source of latency was actually from getting frames off the GPU, then onto the CPU for sending to the USB device.
This is something that I believe is fixable by using different system calls (and making some trade-offs). But I haven't had the time to investigate this properly.
Best,
Dan
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dj311** [comment]
> I'm actually thinking about buying a waveshare hdmi (fpga based) panel. 

To be honest I would do that if I were you. It seems like a lot less faff!
